server_names_hash_bucket_size 64;

server {
    listen 80;
    server_name _;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { return 301 https://$host$request_uri; }
}

# Asosiy domen
server {
    listen 443 ssl;
    http2 on;
    server_name darspilot.com www.darspilot.com;

    ssl_certificate     /etc/letsencrypt/live/darspilot.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/darspilot.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:10m;

    root /usr/share/nginx/html;
    index index.html;
    client_max_body_size 40m;

    location /api/ {
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }
    location /assets/ { expires 7d; add_header Cache-Control "public, immutable"; }
    location / { try_files $uri $uri/ /index.html; }

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
}

# Zaxira havola: IP va sslip.io
server {
    listen 443 ssl default_server;
    http2 on;
    server_name _;

    ssl_certificate     /etc/letsencrypt/live/189-74-97-73.sslip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/189-74-97-73.sslip.io/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:10m;

    root /usr/share/nginx/html;
    index index.html;
    client_max_body_size 40m;

    location /api/ {
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }
    location /assets/ { expires 7d; add_header Cache-Control "public, immutable"; }
    location / { try_files $uri $uri/ /index.html; }

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
}
